app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'Admin\AdminController@dashboard');

Route::get('/admin/dashboard', [
    'as' => 'dashboard', 'uses' => 'Admin\AdminController@dashboard'
]);

Route::auth();


Route::group(array('middleware' => 'auth'), function () {
    //Login Routes...
    Route::get('/employee/login',[
    'as'=> 'employee.login', 'uses'=>'EmployeeAuth\AuthController@showLoginForm']);
    Route::post('/employee/login','EmployeeAuth\AuthController@login');
    Route::get('/employee/logout',[ 'as'=>'employee.logout', 'uses'=>'EmployeeAuth\AuthController@logout']);

    // Registration Routes...
    Route::get('employee/register', 'EmployeeAuth\AuthController@showRegistrationForm');
    Route::post('employee/register', 'EmployeeAuth\AuthController@register');

    Route::post('employee/password/email','EmployeeAuth\PasswordController@sendResetLinkEmail');
    Route::post('employee/password/reset','EmployeeAuth\PasswordController@reset');
    Route::get('employee/password/reset/{token?}','EmployeeAuth\PasswordController@showResetForm');

    Route::get('/employee', 'EmployeeController@index');
});

Route::get('/employee/dashboard', [
    'as' => 'employee.dashboard', 'uses' => 'EmployeeController@dashboard'
]);



/*Route::group(array('middleware' => 'auth'), function() {

    Route::get('/admin/dashboard', ['as' => 'dashboard', 'uses' => 'Admin\AdminController@dashboard']);

});*/
Route::get('/admin', [
    'as' => 'admin', 'uses' => 'Admin\AdminController@index'
]);
Route::get('/admin/additem', [
    'as' => 'addItem', 'uses' => 'Admin\AdminController@addItem'
]);

Route::resource('admin/groups', 'Admin\Groups\GroupsController');

Route::resource('admin/product', 'Admin\ProductController');


Route::get('getImport', 'Admin\ExcelController@getImport');
Route::post('admin/postImport', 'Admin\ExcelController@postImport');

resources/views/admin/include/footer.blade.php
<!-- Top Bar Start -->
<div class="topbar">

    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="index.html" class="logo">
                <i class="zmdi zmdi-toys icon-c-logo"></i><span>Flac<span>to</span></span>
                <!--<span><img src="assets/images/logo.png" alt="logo" style="height: 20px;"></span>-->
            </a>
        </div>
    </div>

    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="">
                <div class="pull-left">
                    <button class="button-menu-mobile open-left waves-effect waves-light">
                        <i class="zmdi zmdi-menu"></i>
                    </button>
                    <span class="clearfix"></span>
                </div>

                <form role="search" class="navbar-left app-search pull-left hidden-xs">
                    <input type="text" placeholder="Search..." class="form-control">
                    <a href=""><i class="fa fa-search"></i></a>
                </form>


                <ul class="nav navbar-nav navbar-right pull-right">
                    <li>
                        <!-- Notification -->
                        <div class="notification-box">
                            <ul class="list-inline m-b-0">
                                <li>
                                    <a href="javascript:void(0);" class="right-bar-toggle">
                                        <i class="zmdi zmdi-notifications-none"></i>
                                    </a>
                                    <div class="noti-dot">
                                        <span class="dot"></span>
                                        <span class="pulse"></span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <!-- End Notification bar -->
                    </li>

                    <li class="dropdown user-box">
                        <a href="" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown" aria-expanded="true">
                            <img src="assets/images/users/avatar-1.jpg" alt="user-img" class="img-circle user-img">
                            <div class="user-status away"><i class="zmdi zmdi-dot-circle"></i></div>
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="javascript:void(0)"><i class="ti-user m-r-5"></i> Profile</a></li>
                            <li><a href="javascript:void(0)"><i class="ti-settings m-r-5"></i> Settings</a></li>
                            <li><a href="javascript:void(0)"><i class="ti-lock m-r-5"></i> Lock screen</a></li>
                            <li><a href="javascript:void(0)"><i class="ti-power-off m-r-5"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>

            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<!-- Top Bar End -->

resources/views/admin/include/head.blade.php
@section('topbar')
        <!-- Top Bar Start -->
<div class="topbar">

    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="index.html" class="logo">
                {{--<i class="zmdi zmdi-toys icon-c-logo"></i><span>Flac<span>to</span></span>--}}
                <span><img src="{{ URL('assets/admin/images/logo.png') }}" alt="logo" style="height: 32px;" ></span>
            </a>
        </div>
    </div>

    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="">
                <div class="pull-left">
                    <button class="button-menu-mobile open-left waves-effect waves-light">
                        <i class="zmdi zmdi-menu"></i>
                    </button>
                    <span class="clearfix"></span>
                </div>



                <ul class="nav navbar-nav navbar-right pull-right">
                    <li>
                        <!-- Notification -->
                        <div class="notification-box">
                            <ul class="list-inline m-b-0">
                                <li>
                                    <a href="javascript:void(0);" class="right-bar-toggle">
                                        <i class="zmdi zmdi-notifications-none"></i>
                                    </a>
                                    <div class="noti-dot">
                                        <span class="dot"></span>
                                        <span class="pulse"></span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <!-- End Notification bar -->
                    </li>

                    <li class="dropdown user-box">
                        <a href="" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown" aria-expanded="true">
                            <img src="{{ URL('assets/admin/images/users/avatar-1-32.png') }}" alt="user-img" class="img-circle user-img">
                            <div class="user-status away"><i class="zmdi zmdi-dot-circle"></i></div>
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="javascript:void(0)"><i class="ti-user m-r-5"></i> Profile</a></li>
                            {{--<li><a href="javascript:void(0)"><i class="ti-settings m-r-5"></i> Settings</a></li>
                            <li><a href="javascript:void(0)"><i class="ti-lock m-r-5"></i> Lock screen</a></li>--}}

                            <li><a href="@if(auth('employee')->user()) {{ url('employee/logout') }} @else {{ url('/logout') }} @endif"><i class="ti-power-off m-r-5"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>

            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<!-- Top Bar End -->
@endsection

resources/views/admin/include/header.blade.php
@section('favicon')
    <link rel="shortcut icon" href="{{ URL('assets/admin/images/favicon.png') }}">
@endsection
@section('head_script')
{{ Html::style('/assets/admin/css/bootstrap.min.css') }}

{{ Html::style('/assets/admin/css/menu.css') }}

{{ Html::style('/assets/admin/css/core.css') }}

{{ Html::style('/assets/admin/css/components.css') }}

{{ Html::style('/assets/admin/css/icons.css') }}

{{ Html::style('/assets/admin/css/pages.css') }}

{{ Html::style('/assets/admin/css/responsive.css') }}

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

{{ Html::script('/assets/admin/js/modernizr.min.js') }}
@endsection

@section('bottom_script')
<script>
    var resizefunc = [];
</script>

<!-- jQuery  -->
{{ Html::script('/assets/admin/js/jquery.min.js') }}
{{ Html::script('/assets/admin/js/bootstrap.min.js') }}
{{ Html::script('/assets/admin/js/detect.js') }}
{{ Html::script('/assets/admin/js/fastclick.js') }}
{{ Html::script('/assets/admin/js/jquery.slimscroll.js') }}
{{ Html::script('/assets/admin/js/jquery.blockUI.js') }}
{{ Html::script('/assets/admin/js/waves.js') }}
{{ Html::script('/assets/admin/js/wow.min.js') }}
{{ Html::script('/assets/admin/js/jquery.nicescroll.js') }}
{{ Html::script('/assets/admin/js/jquery.scrollTo.min.js') }}

        <!-- Validation js (Parsleyjs) -->
{{ Html::script('/assets/admin/plugins/parsleyjs/dist/parsley.min.js') }}

        <!-- App js -->
{{ Html::script('/assets/admin/js/jquery.core.js') }}
{{ Html::script('/assets/admin/js/jquery.app.js') }}
@endsection

resources/views/admin/include/sidebar.blade.php
@section('left_sidebar')
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>



                <li class="has_sub">
                    <a href="{{route('dashboard')}}" class="waves-effect"><i class="ti-dashboard"></i> <span> Dashboard </span> </a>
                </li>

                <li class="has_sub">
                    <a href="{{url('/admin/groups/')}}" class="waves-effect"><i class="ti-package"></i> <span> Groups</span> </a>
                    <ul class="list-unstyled">
                        <li><a href="{{route('admin.groups.create')}}">Add Group</a></li>
                        <li><a href="{{url('/admin/groups/')}}">Manage Groups</a></li>
                    </ul>

                </li>


                <li class="has_sub">
                    <a href="{{url('/admin/product/')}}" class="waves-effect"><i class="ti-plus"></i> <span> Product</span> </a>
                    <ul class="list-unstyled">
                        <li><a href="{{route('admin.product.create')}}">Add Product</a></li>
                        <li><a href="{{url('/admin/product/')}}">View all Products</a></li>
                    </ul>

                </li>

                {{--<li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect active"><i class="zmdi zmdi-collection-text"></i><span class="label label-default pull-right">4</span><span> Forms </span> </a>
                    <ul class="list-unstyled">
                        <li><a href="form-elements.html">Form Elements</a></li>
                        <li><a href="form-advanced.html">Advanced Form</a></li>
                        <li class="active"><a href="form-validation.html">Form Validation</a></li>
                        <li><a href="form-wizard.html">Form Wizard</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-view-list"></i> <span> Tables </span> </a>
                    <ul class="list-unstyled">
                        <li><a href="tables-basic.html">Basic Tables</a></li>
                        <li><a href="tables-datatable.html">Data Table</a></li>
                        <li><a href="tables-editable.html">Editable Table</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-chart"></i><span> Charts </span></a>
                    <ul class="list-unstyled">
                        <li><a href="chart-flot.html">Flot Chart</a></li>
                        <li><a href="chart-morris.html">Morris Chart</a></li>
                        <li><a href="chart-chartist.html">Chartist Charts</a></li>
                        <li><a href="chart-other.html">Other Chart</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-map"></i><span> Maps </span></a>
                    <ul class="list-unstyled">
                        <li><a href="map-google.html">Google Maps</a></li>
                        <li><a href="map-vector.html">Vector Maps</a></li>
                    </ul>
                </li>

                <li class="text-muted menu-title">More</li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span class="label label-default pull-right">7</span><span> Pages </span></a>
                    <ul class="list-unstyled">
                        <li><a href="page-starter.html">Starter Page</a></li>
                        <li><a href="page-login.html">Login</a></li>
                        <li><a href="page-register.html">Register</a></li>
                        <li><a href="page-recoverpw.html">Recover Password</a></li>
                        <li><a href="page-lock-screen.html">Lock Screen</a></li>
                        <li><a href="page-confirm-mail.html">Confirm Mail</a></li>
                        <li><a href="page-404.html">Error 404</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="ti-share"></i><span>Multi Level </span></a>
                    <ul>
                        <li class="has_sub">
                            <a href="javascript:void(0);" class="waves-effect"><span>Menu Level 1.1</span> </a>
                            <ul style="">
                                <li><a href="javascript:void(0);"><span>Menu Level 2.1</span></a></li>
                                <li><a href="javascript:void(0);"><span>Menu Level 2.2</span></a></li>
                                <li><a href="javascript:void(0);"><span>Menu Level 2.3</span></a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="javascript:void(0);"><span>Menu Level 1.2</span></a>
                        </li>
                    </ul>
                </li>
--}}
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- Left Sidebar End -->
@endsection


@section('right_sidebar')
        <!-- Right Sidebar -->
<div class="side-bar right-bar">
    <a href="javascript:void(0);" class="right-bar-toggle">
        <i class="zmdi zmdi-close-circle-o"></i>
    </a>
    <h4 class="">Notifications</h4>
    <div class="notification-list nicescroll">
        <ul class="list-group list-no-border user-list">
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="avatar">
                        <img src="{{ URL('assets/admin/images/users/avatar-1-32.png') }}" alt="">
                    </div>
                    <div class="user-desc">
                        <span class="name">Michael Zenaty</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">2 hours ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="icon">
                        <i class="zmdi zmdi-account"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">New Signup</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">5 hours ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="icon">
                        <i class="zmdi zmdi-comment"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">New Message received</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">1 day ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="avatar">
                        <img src="{{ URL('assets/admin/images/users/avatar-1-32.png') }}" alt="">
                    </div>
                    <div class="user-desc">
                        <span class="name">James Anderson</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">2 days ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item active">
                <a href="#" class="user-list-item">
                    <div class="icon">
                        <i class="zmdi zmdi-settings"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">Settings</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">1 day ago</span>
                    </div>
                </a>
            </li>

        </ul>
    </div>
</div>

<!-- /Right-bar -->
@endsection